import "./global.css";
import type { Metadata } from "next";
import ReactQueryProviders from "@/provider/reactQueryProviders";
import { ReactNode } from "react";
import MobileBottomNav from "@/components/mobileBottomNav/MobileBottomNav";
import EmotionThemeProvider from "@/provider/EmotionThemeProvider";
import KakaoScript from "@/utils/kakaoScript";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    Kakao: any;
  }
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          as="style"
          crossOrigin="anonymous"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css"
        />
      </head>
      <body suppressHydrationWarning={true}>
        <ReactQueryProviders>
          <EmotionThemeProvider>
            <div id="portal" />
            {children}
          </EmotionThemeProvider>
          <MobileBottomNav />
        </ReactQueryProviders>
      </body>
      <KakaoScript />
    </html>
  );
}
