import "./global.css";
import type { Metadata } from "next";
import ReactQueryProviders from "@/provider/reactQueryProviders";
import { ReactNode } from "react";
import MobileBottomNav from "@/components/mobileBottomNav/MobileBottomNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ReactQueryProviders>
          {children}
          <MobileBottomNav />
        </ReactQueryProviders>
      </body>
    </html>
  );
}
