name: Front Server (CI)

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Get Github Actions IP Addresses
        id: publicip
        run: |
          response=$(curl -s canhazip.com)
          echo "ip=$response" >> "$GITHUB_OUTPUT"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_2 }}
          aws-region: ap-northeast-2

      - name: Create .env file with secrets
        run: |
          echo "NEXT_PUBLIC_ENDPOINT_EXTERNAL=${{ secrets.NEXT_PUBLIC_ENDPOINT_EXTERNAL }}" >> .env
          echo "NEXT_PUBLIC_IMAGE_DOMAIN=${{ secrets.NEXT_PUBLIC_IMAGE_DOMAIN }}" >> .env
          echo "NEXT_PUBLIC_KAKAO_API_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_API_KEY }}" >> .env
        env:
          NEXT_PUBLIC_ENDPOINT_EXTERNAL: ${{ secrets.NEXT_PUBLIC_ENDPOINT_EXTERNAL }}
          NEXT_PUBLIC_IMAGE_DOMAIN: ${{ secrets.NEXT_PUBLIC_IMAGE_DOMAIN }}
          NEXT_PUBLIC_KAKAO_API_KEY: ${{ secrets.NEXT_PUBLIC_KAKAO_API_KEY }}

      - name: Add GitHub Actions IP
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.SECURITY_GROUP_ID_2 }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.publicip.outputs.ip }}/32

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1

      - name: Build, tag, and push docker image to Amazon ECR Public
        id: docker-builder
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: ${{ secrets.ECR_REGISTRY_ALIAS }}
          REPOSITORY: purple-front-ecr
          IMAGE_TAG: latest
        run: |
          export DOCKER_TAG=$REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
          echo "build start"
          docker build -t $DOCKER_TAG .
          echo "build finish and push start"
          docker push $DOCKER_TAG
          echo "push finish"
          echo "::set-output name=DOCKER_TAG::$DOCKER_TAG"
          echo "push completed"

      - name: Logout of Amazon ECR
        run: docker logout ${{ env.ECR_REGISTRY }}

      - name: Install Docker if not present
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_2 }}
          script: |
            if ! command -v docker >/dev/null 2>&1; then
              echo "Installing Docker..."
              sudo apt-get update
              sudo apt-get install -y docker.io
            else
              echo "Docker already installed."
            fi
            if ! command -v docker-compose >/dev/null 2>&1; then
              echo "Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            else
              echo "Docker Compose already installed."
            fi


      - name: SSH to EC2 Instance and Update Docker Container
        uses: appleboy/ssh-action@master
        env:
          TAG: ${{ steps.docker-builder.outputs.DOCKER_TAG }}
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_2 }}
          envs: TAG
          script: |
            CONTAINER_ID=$(docker ps -q --filter ancestor=$TAG)
            IMAGE_ID=$(docker images --format "{{.ID}}" $TAG)
            if [ ! -z "$CONTAINER_ID" ]; then
              echo "Already run docker exist, stop this container"
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi
            if [ ! -z "$IMAGE_ID" ]; then
              echo "Already docker images exist, remove"
              sudo docker rmi $IMAGE_ID
            fi
            sudo docker pull $TAG
            sudo docker run -d -p 3000:3000 $TAG

      - name: Remove GitHub Actions IP
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.SECURITY_GROUP_ID_2 }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.publicip.outputs.ip }}/32
